import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8787';
type Log={id:number;service_name:string;timestamp:string;status_code:number;latency_ms:number|null;agent:string;region:string;is_valid:number};
function App(){const [open,setOpen]=useState(true),[file,setFile]=useState<File|null>(null),[from,setFrom]=useState(''),[to,setTo]=useState(''),[stats,setStats]=useState<any>(null),[logs,setLogs]=useState<Log[]>([]),[message,setMessage]=useState('');
const query=()=>{const p=new URLSearchParams();if(from)p.set('from',from);if(to)p.set('to',to);Promise.all([fetch(`${API}/api/stats?${p}`).then(r=>r.json()),fetch(`${API}/api/logs?${p}&limit=200`).then(r=>r.json())]).then(([s,l])=>{setStats(s);setLogs(l.rows||[])}).catch(e=>setMessage(e.message))}; useEffect(query,[from,to]);
const upload=async()=>{if(!file)return;setMessage('Uploading and processing...');const fd=new FormData();fd.append('file',file);const r=await fetch(`${API}/api/upload`,{method:'POST',body:fd});const d=await r.json();setMessage(r.ok?`Processed ${d.parsed} rows. Inserted ${d.inserted}; duplicates ${d.duplicates}; rejected ${d.rejected}.`:d.error);query()};
return <main><header><div><p className="eyebrow">EarthRe • SLA Monitoring</p><h1>Health Check Dashboard</h1><p className="muted">Upload monitoring logs, clean them in the cloud, and inspect availability.</p></div><div className="upload"><input type="file" accept=".csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><button onClick={upload} disabled={!file}>Upload CSV</button></div></header>
<section className="filters"><label>From <input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To <input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="secondary" onClick={()=>{setFrom('');setTo('')}}>Clear</button></section>
<section className="card"><button className="collapse" onClick={()=>setOpen(!open)}><span>Statistics</span><span>{open?'▲':'▼'}</span></button>{open&&stats&&<div className="stats">{[['Availability',`${Number(stats.availability||0).toFixed(3)}%`],['Total checks',stats.total],['Successful',stats.success],['Failed',stats.failed],['Invalid',stats.invalid],['Avg latency',`${Number(stats.avg_latency||0).toFixed(1)} ms`],['P95 latency',stats.p95_latency==null?'—':`${Number(stats.p95_latency).toFixed(1)} ms`]].map(([a,b])=><div className="stat" key={String(a)}><span>{a}</span><strong>{b}</strong></div>)}</div>}</section>
<section className="card"><div className="section-title"><h2>Logs</h2><span>{logs.length} shown</span></div><div className="table-wrap"><table><thead><tr><th>Timestamp</th><th>Service</th><th>Status</th><th>Latency</th><th>Agent</th><th>Region</th></tr></thead><tbody>{logs.map(x=><tr key={x.id}><td>{new Date(x.timestamp).toLocaleString()}</td><td>{x.service_name}</td><td><span className={`badge ${x.is_valid?'ok':'invalid'}`}>{x.status_code}</span></td><td>{x.latency_ms==null?'—':`${Number(x.latency_ms).toFixed(1)} ms`}</td><td>{x.agent}</td><td>{x.region}</td></tr>)}</tbody></table></div></section>{message&&<div className="toast">{message}</div>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
